project_id = "jfbmvyqjxwfdmvhovyjj"

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.analytics-daily]
verify_jwt = false

[functions.ghl-order-ingest]
verify_jwt = false